# Generated by Django 5.2.6 on 2025-09-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_destino_itinerario_paquete_and_more'),
    ]

    operations = [
    ]
