# Generated by Django 5.2.6 on 2025-09-20 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0002_configuracionglobalreprogramacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tiempo_respuesta_critica', models.IntegerField(default=2, help_text='Tiempo máximo de respuesta para prioridad crítica (horas)')),
                ('tiempo_respuesta_alta', models.IntegerField(default=8, help_text='Tiempo máximo de respuesta para prioridad alta (horas)')),
                ('tiempo_respuesta_media', models.IntegerField(default=24, help_text='Tiempo máximo de respuesta para prioridad media (horas)')),
                ('tiempo_respuesta_baja', models.IntegerField(default=48, help_text='Tiempo máximo de respuesta para prioridad baja (horas)')),
                ('enviar_emails_cliente', models.BooleanField(default=True, help_text='Enviar emails de notificación a clientes')),
                ('enviar_emails_soporte', models.BooleanField(default=False, help_text='Enviar emails de notificación al equipo de soporte')),
                ('asignacion_automatica', models.BooleanField(default=True, help_text='Asignar automáticamente solicitudes a agentes disponibles')),
                ('max_solicitudes_por_agente', models.IntegerField(default=10, help_text='Máximo de solicitudes activas por agente')),
                ('dias_auto_cierre_resueltas', models.IntegerField(default=7, help_text='Días para cerrar automáticamente solicitudes resueltas')),
                ('recordatorio_cliente_dias', models.IntegerField(default=3, help_text='Días para enviar recordatorio al cliente en solicitudes pendientes')),
            ],
            options={
                'verbose_name': 'Configuración de Soporte',
                'verbose_name_plural': 'Configuraciones de Soporte',
                'db_table': 'soporte_configuracion',
            },
        ),
        migrations.CreateModel(
            name='SolicitudSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_ticket', models.CharField(help_text='Número único del ticket (generado automáticamente)', max_length=20, unique=True)),
                ('tipo_solicitud', models.CharField(choices=[('REPROGRAMACION', 'Solicitud de reprogramación'), ('CANCELACION', 'Solicitud de cancelación'), ('INFORMACION', 'Solicitud de información'), ('QUEJA', 'Queja o reclamo'), ('SUGERENCIA', 'Sugerencia de mejora'), ('PROBLEMA_TECNICO', 'Problema técnico'), ('OTRO', 'Otro tipo de consulta')], default='INFORMACION', help_text='Tipo de solicitud realizada', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('EN_PROCESO', 'En proceso'), ('ESPERANDO_CLIENTE', 'Esperando respuesta del cliente'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado'), ('ESCALADO', 'Escalado a supervisor')], default='PENDIENTE', help_text='Estado actual de la solicitud', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', help_text='Prioridad de la solicitud', max_length=10)),
                ('asunto', models.CharField(help_text='Asunto o título de la solicitud', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la solicitud')),
                ('fecha_limite_respuesta', models.DateTimeField(blank=True, help_text='Fecha límite para primera respuesta', null=True)),
                ('fecha_primera_respuesta', models.DateTimeField(blank=True, help_text='Fecha de la primera respuesta del soporte', null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, help_text='Fecha en que se resolvió la solicitud', null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, help_text='Fecha en que se cerró la solicitud', null=True)),
                ('canal_origen', models.CharField(default='WEB_PANEL', help_text='Canal por el cual se originó la solicitud', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Tags separados por comas para categorización', max_length=500)),
                ('satisfaccion_cliente', models.IntegerField(blank=True, choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], help_text='Calificación de satisfacción del cliente (1-5)', null=True)),
                ('comentario_interno', models.TextField(blank=True, help_text='Comentarios internos del equipo de soporte')),
                ('agente_soporte', models.ForeignKey(blank=True, help_text='Agente de soporte asignado al ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(help_text='Cliente que realizó la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_soporte', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(blank=True, help_text='Reserva relacionada con la solicitud (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_soporte', to='reservas.reserva')),
            ],
            options={
                'verbose_name': 'Solicitud de Soporte',
                'verbose_name_plural': 'Solicitudes de Soporte',
                'db_table': 'soporte_solicitud',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MensajeSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mensaje', models.TextField(help_text='Contenido del mensaje')),
                ('es_interno', models.BooleanField(default=False, help_text='Si es True, solo lo ve el equipo de soporte')),
                ('leido_por_cliente', models.BooleanField(default=False, help_text='Si el cliente ha leído este mensaje')),
                ('leido_por_soporte', models.BooleanField(default=False, help_text='Si el equipo de soporte ha leído este mensaje')),
                ('fecha_lectura_cliente', models.DateTimeField(blank=True, help_text='Fecha en que el cliente leyó el mensaje', null=True)),
                ('fecha_lectura_soporte', models.DateTimeField(blank=True, help_text='Fecha en que soporte leyó el mensaje', null=True)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo adjunto al mensaje', null=True, upload_to='soporte/adjuntos/%Y/%m/')),
                ('nombre_archivo_original', models.CharField(blank=True, help_text='Nombre original del archivo adjunto', max_length=255)),
                ('remitente', models.ForeignKey(help_text='Usuario que envió el mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(help_text='Solicitud a la que pertenece este mensaje', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='soporte.solicitudsoporte')),
            ],
            options={
                'verbose_name': 'Mensaje de Soporte',
                'verbose_name_plural': 'Mensajes de Soporte',
                'db_table': 'soporte_mensaje',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudsoporte',
            index=models.Index(fields=['numero_ticket'], name='soporte_sol_numero__aa52f2_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudsoporte',
            index=models.Index(fields=['cliente', 'estado'], name='soporte_sol_cliente_91c3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudsoporte',
            index=models.Index(fields=['agente_soporte', 'estado'], name='soporte_sol_agente__dbbdbe_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudsoporte',
            index=models.Index(fields=['tipo_solicitud', 'prioridad'], name='soporte_sol_tipo_so_86c72e_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudsoporte',
            index=models.Index(fields=['created_at'], name='soporte_sol_created_bdbec8_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudsoporte',
            index=models.Index(fields=['estado', 'prioridad', 'created_at'], name='soporte_sol_estado_44d880_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajesoporte',
            index=models.Index(fields=['solicitud', 'created_at'], name='soporte_men_solicit_76743d_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajesoporte',
            index=models.Index(fields=['remitente', 'created_at'], name='soporte_men_remiten_979c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajesoporte',
            index=models.Index(fields=['leido_por_cliente', 'leido_por_soporte'], name='soporte_men_leido_p_083fa5_idx'),
        ),
    ]
